version: '3'

services:
  postgres-compose:
    container_name: postgres_local
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres22"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
      
  pgadmin:
    container_name: pgadmin_local
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@loomi.com.br"
      PGADMIN_DEFAULT_PASSWORD: "pgAdmin22"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge